name: SimplePortals
main: falkirks\simpleportals\SimplePortals
author: Falkirks
version: 0.0.6
api: [1.10.0,2.0.0,3.0.0-ALPHA5]
depend: ["SimpleWarp"]
permissions:
  simpleportals:
    default: op
    children:
      simpleportals.create:
        default: op
        description: Create a new portal
      simpleportals.use:
        default: true
        description: Use existing portals
